# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_html',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
